// HttpUploader.idl : IDL source for HttpUploader
//

// This file will be processed by the MIDL tool to
// produce the type library (HttpUploader.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(F80C6A56-E036-4AD8-8896-94295D242FC0),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IUploader : IDispatch{
};
[
	uuid(F845713E-D341-4F05-969B-F472EBC22B27),
	version(1.0),
]
library HttpUploaderLib
{
	importlib("stdole2.tlb");
	[
		uuid(7E406662-E762-45BE-9552-51D900C61A14)		
	]
	coclass Uploader
	{
		[default] interface IUploader;
	};
};

